package:
  name: pysoundfile
  version: 0.8.1

source:
  fn: PySoundFile-0.8.1.tar.gz
  url: https://pypi.python.org/packages/51/4d/2c36a6e79d1128b649ab0c32b79365f92f6146ffeb2d4ba0d0c4573826d5/PySoundFile-0.8.1.tar.gz
  md5: 276f26f454848ce7abcf5155c64e7680

requirements:
  build:
    - python
    - setuptools
    - cffi >=0.6

  run:
    - python
    - cffi >=0.6
    - libsndfile

test:
  # Python imports
  imports:
    - soundfile

  requires:
    - pytest

about:
  home: https://github.com/bastibe/PySoundFile
  license: BSD License
  summary: 'An audio library based on libsndfile, CFFI and NumPy'
  license_family: BSD
