package:
  name: pysmb
  version: "1.1.18"

source:
  fn: pysmb-1.1.18.tar.gz
  url: https://pypi.python.org/packages/source/p/pysmb/pysmb-1.1.18.tar.gz
  md5: 9fe70cbc812b2e789915bedea7e45b1a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysmb = pysmb:main
    #
    # Would create an entry point called pysmb that calls pysmb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyasn1

  run:
    - python
    - pyasn1

test:
  # Python imports
  imports:
    - nmb
    - smb
    - smb.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://miketeo.net/projects/pysmb
  license: zlib/libpng License
  summary: 'pysmb is an experimental SMB/CIFS library written in Python to support file sharing between Windows and Linux machines'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
