package:
  name: cassandra-driver
  version: "2.7.2"

source:
  fn: cassandra-driver-2.7.2.tar.gz
  url: https://files.pythonhosted.org/packages/d0/c0/39de7f2b90431179ed55ff210aaed52b31497653456d63a1f14e0e1a63b6/cassandra-driver-2.7.2.tar.gz
  md5: e82c41599892cb5d4f270c98c2062411
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cassandra-driver = cassandra-driver:main
    #
    # Would create an entry point called cassandra-driver that calls cassandra-driver.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - libev
    - numpy
    - setuptools
    - six >=1.6
    - futures
    - cython

  run:
    - python
    - libev
    - numpy
    - six >=1.6
    - futures

test:
  # Python imports
  imports:
    - cassandra
    - cassandra.cqlengine
    - cassandra.io

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock <=1.0.1
    - nose
    - pytz
    - pyyaml
    - sure
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/datastax/python-driver
  license: Apache Software License
  summary: 'Python driver for Cassandra'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
