# Jinja variables help maintain the recipe as you'll update the version only here.
{% set name = "cassandra-driver" %}
{% set version = "2.7.2" %}
{% set sha256 = "f65c7f9f0a552975b28ee370c9f19f8dd881ebd7c208e5818095533440a525df" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: python setup.py build build_ext -I${PREFIX}/include -L${PREFIX}/lib install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - libev
    - numpy x.x
    - setuptools
    - six >=1.6
    - futures <=2.2.0
    - cython <0.25

  run:
    - python
    - libev
    - numpy
    - six >=1.6
    - futures <=2.2.0

test:
  # Python imports
  imports:
    - cassandra
    - cassandra.cqlengine
    - cassandra.io

about:
  home: http://github.com/datastax/python-driver
  license: Apache
  license_family: Apache
  license_file: LICENSE
  summary: 'Python driver for Cassandra'
  description: |
    A modern, feature-rich and highly-tunable Python client library for Apache Cassandra
    (1.2+) and DataStax Enterprise (3.1+) using exclusively Cassandra's binary protocol
    and Cassandra Query Language v3.
  doc_url: http://datastax.github.io/python-driver/api/index.html
  dev_url: http://github.com/datastax/python-driver

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - petercable
