package:
  name: ooi-data
  version: 0.0.5

source:
  git_url: https://github.com/oceanobservatories/ooi-data
  git_rev: v0.0.5

requirements:
  build:
    - python
    - setuptools
  run:
    - python <3
    - setuptools
    - numpy 1.12.0
    - sqlalchemy 1.1.5
    - geoalchemy2 0.4.0

build:
  number: 0

about:
  home: http://oceanobservatories.org
  license: apache 2.0
  summary: Data model for the Ocean Observatories Project
