package:
    name: stream_engine
    version: 1.4.1

source:
    git_url: https://github.com/oceanobservatories/stream_engine
    git_rev: v1.4.1

requirements:
    run:
        - enginemeta

about:
    summary: Stream engine
