package:
    name: stream_engine
    version: 1.3.9

source:
    git_url: https://github.com/oceanobservatories/stream_engine
    git_rev: v1.3.9

requirements:
    run:
        - enginemeta

about:
    summary: Stream engine
