package:
  name: qpid-python
  version: "0.32"

source:
  fn: qpid-python-0.32.tar.gz
  url: http://download.nextag.com/apache/qpid/0.32/qpid-python-0.32.tar.gz
  md5: 7d6d1d2938fcd9e5a19423123b800179

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - mllib
    - qpid
    - qpid.messaging
    - qpid.tests
    - qpid.tests.messaging

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://qpid.apache.org/
  license: Apache Software License
  summary: 'Python client implementation for Apache Qpid'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
