package:
    name: ingest_engine
    version: 1.1.3

source:
    git_url: ssh://uframe-cm.ooi.rutgers.edu:29418/ingest_engine
    git_rev: v1.1.3

requirements:
    run:
        - enginemeta

about:
    summary: Ingest engine
