package:
  name: amqp
  version: "1.4.9"

source:
  fn: amqp-1.4.9.tar.gz
  url: https://pypi.python.org/packages/cc/a4/f265c6f9a7eb1dd45d36d9ab775520e07ff575b11ad21156f9866da047b2/amqp-1.4.9.tar.gz
  md5: df57dde763ba2dea25b3fa92dfe43c19
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - amqp = amqp:main
    #
    # Would create an entry point called amqp that calls amqp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - amqp
    - amqp.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage >=3.0
    - mock
    - nose
    #- nose-cover3
    #- unittest2 >=0.4.0
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/celery/py-amqp
  license: GNU Library or Lesser General Public License (LGPL) or BSD License
  summary: 'Low-level AMQP client for Python (fork of amqplib)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
