package:
  name: python-consul
  version: "0.6.0"

source:
  fn: python-consul-0.6.0.tar.gz
  url: https://files.pythonhosted.org/packages/1d/75/17bfc3aa64a4be11ef3a5e8211f8177a44d6a5cd323b64f8d451e9d59b71/python-consul-0.6.0.tar.gz
  md5: 662cd08d348d14aad9d31d1dc5d9b16f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-consul = python-consul:main
    #
    # Would create an entry point called python-consul that calls python-consul.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests
    - six >=1.4

  run:
    - python
    - requests
    - six >=1.4

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cablehead/python-consul
  license: MIT License
  summary: 'Python client for Consul (http://www.consul.io/)'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
