package:
  name: ion-functions
  version: 2.1.1

source:
  git_url: https://github.com/ooici/ion-functions
  git_rev: 38e9637db7f9dddd8ee18d7f4f7d20aa0c7bc879

requirements:
  build:
    - python
    - setuptools
    - setuptools_cython
    - cython
    - numpy
  run:
    # conda default channel
    - python
    - setuptools
    - ipython
    - scipy
    - numexpr
    # conda ooi channel
    - geomag
    - pygsw

build:
  number: 1

about:
  home: http://oceanobservatories.org
  license: apache 2.0
  summary: Functions for OOI

