package:
  name: libogg
  version: 1.3.2

source:
  url: http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
  sha256: 3f687ccdd5ac8b52d76328fbbfebc70c459a40ea891dbf3dccb74a210826e79b

build:
  number: 0

about:
  home: https://xiph.org/ogg/
  license: Modified BSD
  summary: Ogg is a multimedia container format, and the native file and stream format for the Xiph.org multimedia codecs. 
