package:
  name: ooi-status
  version: 1.0.3

source:
  git_url: https://github.com/oceanobservatories/ooi-status
  git_rev: v1.0.3

requirements:
  build:
    - python
    - setuptools
  run:
    - python <3
    - setuptools
    - click 6.7
    - apscheduler 3.3.1
    - geoalchemy2 0.3.0
    - flask 0.12
    - gevent 1.2.1
    - gunicorn 19.1.0
    - numpy 1.11.3
    - pandas 0.19.2
    - psycopg2 2.6.2
    - requests 2.12.4
    - sqlalchemy 1.1.5
    - cachetools 2.0.0

build:
  number: 0

about:
  home: http://oceanobservatories.org
  license: apache 2.0
  summary: Status Monitor for the Ocean Observatories Project
