package:
  name: libgswteos
  version: 3.03

source:
  git_url: https://github.com/oceanobservatories/GSW-C.git
  git_rev: 99f39bcbe6169064b7a7078fac84181e9e7d96b3

build:
  number: 0

about:
  home: http://teos-10.org
  license: teos
  summary: TEOS-10 V3.03 GSW Oceanographic Toolbox in C
