package:
  name: libvorbis
  version: 1.3.5

source:
  url: http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz
  sha256: 54f94a9527ff0a88477be0a71c0bab09a4c3febe0ed878b24824906cd4b0e1d1

build:
  number: 0

requirements:
  build:
    - libogg
  run:
    - libogg

about:
  home: https://xiph.org/vorbis/
  license: Modified BSD
  summary: Ogg Vorbis is a fully open, non-proprietary, patent-and-royalty-free, general-purpose compressed audio format for mid to high quality (8kHz-48.0kHz, 16+ bit, polyphonic) audio and music at fixed and variable bitrates from 16 to 128 kbps/channel.
