package:
  name: kombu
  version: "3.0.35"

source:
  fn: kombu-3.0.35.tar.gz
  url: https://pypi.python.org/packages/5f/4f/3859b52f6d465d0d4a767516c924ee4f0e1387498ac8d0c30d9942da3762/kombu-3.0.35.tar.gz
  md5: 6483ac8ba7109ec606f5cb9bd084b6ef
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - kombu = kombu:main
    #
    # Would create an entry point called kombu that calls kombu.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - anyjson >=0.3.3
    - amqp >=1.4.9,<2.0

  run:
    - python
    - anyjson >=0.3.3
    - amqp >=1.4.9,<2.0

about:
  home: http://kombu.readthedocs.org
  license: BSD License
  summary: 'Messaging library for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
