package:
  name: ooi_port_agent
  version: 0.0.37

source:
  git_url: https://github.com/oceanobservatories/ooi_port_agent
  git_rev: 405cdd78d2786c4c2e4168ec0c3a2c5bc1fc12a1

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    # default channel
    - python
    - cython
    - twisted
    - docopt
    - pyyaml
    - click
    # ooi channel
    - pika ==0.10.0
    - pysmb ==1.1.18

build:
  number: 0

about:
  home: http://oceanobservatories.org
  license: apache 2.0
  summary: Port Agent for the Ocean Observatories Project
