package:
  name: ooi_port_agent
  version: 0.0.33

source:
  git_url: https://github.com/oceanobservatories/ooi_port_agent
  git_rev: d02bc7dec15548cb4293a78756262e799c1807b7

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    # default channel
    - python
    - cython
    - twisted
    - docopt
    - pyyaml
    - click
    # ooi channel
    - pika ==0.10.0
    - pysmb ==1.1.18

build:
  number: 0

about:
  home: http://oceanobservatories.org
  license: apache 2.0
  summary: Port Agent for the Ocean Observatories Project
